/**
 * 앱 컴포넌트 레지스트리
 * 새로운 앱을 추가할 때 여기에만 등록하면 됩니다.
 */

import React from 'react'
import dynamic from 'next/dynamic'

// 앱 컴포넌트 타입
type AppComponent = React.ComponentType

// 앱 레지스트리 맵
const appComponents: Record<string, () => Promise<{ default: AppComponent }>> = {
  'wireless-tech-detective': () => import('./wireless-tech-detective/WirelessTechDetectiveApp'),
  'smart-pairing': () => import('./smart-pairing/SmartPairingApp'),
  'network-device-guide': () => import('./network-device-guide/NetworkDeviceGuideApp'),
  'master-ip-decoder': () => import('./master-ip-decoder/MasterIPDecoderApp'),
  'network-master': () => import('./network-master/NetworkMasterApp'),
  'address-revolution': () => import('./address-revolution/AddressRevolutionApp'),
  'iot-builder-academy': () => import('./iot-builder-academy/IoTBuilderAcademyApp'),
  'iot-project-planner': () => import('./iot-project-planner/IoTProjectPlannerApp'),
  'iot-data-flow-simulator': () => import('./iot-data-flow-simulator/IoTDataFlowSimulatorApp'),
  'iot-explorer': () => import('./iot-explorer/IoTExplorerApp'),
  'audio-compress-lab': () => import('./audio-compress-lab/AudioCompressLabApp'),
  'data-cruncher-academy': () => import('./data-cruncher-academy/DataCruncherAcademyApp'),
  'image-pixel-lab': () => import('./image-pixel-lab/ImagePixelLabApp'),
  'huffman-forest': () => import('./huffman-forest/HuffmanForestApp'),
  'sns-detective': () => import('./sns-detective/SNSDetectiveApp'),
  'data-analyst-simulator': () => import('./data-analyst-simulator/DataAnalystSimulatorApp'),
  'big-data-master': () => import('./big-data-master/BigDataMasterApp'),
  'scytale-cipher-lab': () => import('./scytale-cipher-lab/ScytaleCipherLabApp'),
  'crypto-lab': () => import('./crypto-lab/CryptoLabApp'),
  'algorithm-racing': () => import('./algorithm-racing/AlgorithmRacingApp'),
  'dataviz-master': () => import('./dataviz-master/DataVizMasterApp'),
  'cipher-master': () => import('./cipher-master/CipherMasterApp'),
  'cryptolearn': () => import('./cryptolearn/CryptoLearnApp'),
  'data-tycoon': () => import('./data-tycoon/DataTycoonApp'),
  'crypto-hacker': () => import('./crypto-hacker/CryptoHackerApp'),
  'threat-database': () => import('./threat-database/ThreatDatabaseApp'),
  'copyright-sharing-world': () => import('./copyright-sharing-world/CopyrightSharingWorldApp'),
  'info-security-guardian': () => import('./info-security-guardian/InfoSecurityGuardianApp'),
  'info-protection-castle': () => import('./info-protection-castle/InfoProtectionCastleApp'),
  'my-ai-career-compass': () => import('./my-ai-career-compass/MyAICareerCompassApp'),
  'digital-detective': () => import('./digital-detective/DigitalDetectiveApp'),
  'future-farm-tycoon': () => import('./future-farm-tycoon/FutureFarmTycoonApp'),
  'smart-life': () => import('./smart-life/SmartLifeApp'),
  'job-time-machine': () => import('./job-time-machine/JobTimeMachineApp'),
  '3버튼-긴급신고-위저드': () => import('./3버튼-긴급신고-위저드/App'),
  '4단계-진로-설계-위저드': () => import('./4단계-진로-설계-위저드/App'),
  '5단계-파이프라인-퍼즐_-우리-반-화재-경보기-설계실': () => import('./5단계-파이프라인-퍼즐_-우리-반-화재-경보기-설계실/App'),
  'ai-assembly-line': () => import('./ai-assembly-line/App'),
  'ai-battle-arena': () => import('./ai-battle-arena/App'),
  'ai-history-maker_-from-rules-to-data': () => import('./ai-history-maker_-from-rules-to-data/App'),
  'ai-서비스-파이프라인-퍼즐': () => import('./ai-서비스-파이프라인-퍼즐/App'),
  'ai-선생님_-정답을-알려줘': () => import('./ai-선생님_-정답을-알려줘/App'),
  'ai-테크-마스터': () => import('./ai-테크-마스터/App'),
  'ai-할까-내가-할까': () => import('./ai-할까-내가-할까/App'),
  'algorithm-delivery-service': () => import('./algorithm-delivery-service/App'),
  'autoagent-sim': () => import('./autoagent-sim/App'),
  'bodycheck_-나의-건강-데이터-변수-연구소': () => import('./bodycheck_-나의-건강-데이터-변수-연구소/App'),
  'bubble-sort-speedrun_-adjacency-comparison-lab': () => import('./bubble-sort-speedrun_-adjacency-comparison-lab/App'),
  'cafecoder_-나만의-키오스크-만들기': () => import('./cafecoder_-나만의-키오스크-만들기/App'),
  'classmanager': () => import('./classmanager/App'),
  'cleanpipe-puzzle': () => import('./cleanpipe-puzzle/App'),
  'cluster-manager_-choosing-k': () => import('./cluster-manager_-choosing-k/App'),
  'code-master_-moving-classroom': () => import('./code-master_-moving-classroom/App'),
  'collect-or-not': () => import('./collect-or-not/App'),
  'computable-or-not': () => import('./computable-or-not/App'),
  'cvs-manager-편의점-재고-매니저': () => import('./cvs-manager-편의점-재고-매니저/App'),
  'data-chef_-ai-요리하기': () => import('./data-chef_-ai-요리하기/App'),
  'data-detective-xy': () => import('./data-detective-xy/App'),
  'datasort_-데이터-분리수거-대작전': () => import('./datasort_-데이터-분리수거-대작전/App'),
  'digital-concept-master': () => import('./digital-concept-master/App'),
  'etl-마스터_-데이터-파이프라인-퍼즐': () => import('./etl-마스터_-데이터-파이프라인-퍼즐/App'),
  'graph-modeling-playground': () => import('./graph-modeling-playground/App'),
  'graph-wizard_-chart-sorcerer': () => import('./graph-wizard_-chart-sorcerer/App'),
  'huffman-tree-maker': () => import('./huffman-tree-maker/App'),
  'infosec-habit-streak': () => import('./infosec-habit-streak/App'),
  'iot-메이커-스페이스_-우리-학교-업그레이드': () => import('./iot-메이커-스페이스_-우리-학교-업그레이드/App'),
  'iot-탐정-아카데미': () => import('./iot-탐정-아카데미/App'),
  'iot-파이어가드_-학교를-지켜라': () => import('./iot-파이어가드_-학교를-지켜라/App'),
  'ip-hacker_-binary-decoder': () => import('./ip-hacker_-binary-decoder/App'),
  'k-means-lab': () => import('./k-means-lab/App'),
  'k-nn-거리-게임': () => import('./k-nn-거리-게임/App'),
  'k-평균-순서-퍼즐': () => import('./k-평균-순서-퍼즐/App'),
  'labeling-master_-ai-teacher': () => import('./labeling-master_-ai-teacher/App'),
  'logicloop_-ai-thinking-puzzles': () => import('./logicloop_-ai-thinking-puzzles/App'),
  'lz-패턴-탐정': () => import('./lz-패턴-탐정/App'),
  'marketing-cluster-wizard': () => import('./marketing-cluster-wizard/App'),
  'medi-check-logic_-ai-건강검진-판독기': () => import('./medi-check-logic_-ai-건강검진-판독기/App'),
  'ml-detective': () => import('./ml-detective/App'),
  'ml-pipeline-puzzle': () => import('./ml-pipeline-puzzle/index'),
  'ml-판별-배틀': () => import('./ml-판별-배틀/App'),
  'model-selection-trade-off-challenge': () => import('./model-selection-trade-off-challenge/App'),
  'netfixer': () => import('./netfixer/App'),
  'netmaster_-유선-vs-무선': () => import('./netmaster_-유선-vs-무선/App'),
  'network-puzzle_-photo-journey': () => import('./network-puzzle_-photo-journey/App'),
  'ocean-clean-ai': () => import('./ocean-clean-ai/App'),
  'packet-express_-seoul-to-harvard': () => import('./packet-express_-seoul-to-harvard/App'),
  'panlanmanwan-분류-게임': () => import('./panlanmanwan-분류-게임/App'),
  'pixellog_-2차원-배열로-그리는-그림': () => import('./pixellog_-2차원-배열로-그리는-그림/App'),
  'preprocess-microlab': () => import('./preprocess-microlab/App'),
  'queuequest-collector': () => import('./queuequest-collector/App'),
  'rle-픽셀아트-압축-실험실': () => import('./rle-픽셀아트-압축-실험실/App'),
  'robolearn_-ai-agent-simulation': () => import('./robolearn_-ai-agent-simulation/App'),
  'rpg-히어로-팩토리': () => import('./rpg-히어로-팩토리/App'),
  'school-lunch-bot': () => import('./school-lunch-bot/App'),
  'school-robot-lab_-intelligent-agents': () => import('./school-robot-lab_-intelligent-agents/App'),
  'sdgs-ai-project-wizard': () => import('./sdgs-ai-project-wizard/App'),
  'secretlog_-나만의-파이썬-일기장': () => import('./secretlog_-나만의-파이썬-일기장/App'),
  'share-or-shield': () => import('./share-or-shield/App'),
  'smart-class-builder': () => import('./smart-class-builder/App'),
  'smart-farm-logic-lab': () => import('./smart-farm-logic-lab/App'),
  'smart-recommender': () => import('./smart-recommender/App'),
  'sns-해킹-방어-실험실_-내-계정-지키기': () => import('./sns-해킹-방어-실험실_-내-계정-지키기/App'),
  'solomons-choice_-ai-ethics-court': () => import('./solomons-choice_-ai-ethics-court/App'),
  'sort-racer': () => import('./sort-racer/App'),
  'sortalgo-trade-off-coach': () => import('./sortalgo-trade-off-coach/App'),
  'sweetness-galaxy': () => import('./sweetness-galaxy/App'),
  'teamplay_-human-x-ai-simulator': () => import('./teamplay_-human-x-ai-simulator/App'),
  'the-anonymizer-가명-정보-공작소': () => import('./the-anonymizer-가명-정보-공작소/App'),
  'unsupervised-explorer': () => import('./unsupervised-explorer/App'),
  'unsupervised-wizard': () => import('./unsupervised-wizard/App'),
  'up_down-탐색-실험실': () => import('./up_down-탐색-실험실/App'),
  'viz-daily-mission': () => import('./viz-daily-mission/App'),
  'wireless-detective_-신호를-찾아라': () => import('./wireless-detective_-신호를-찾아라/App'),
  'xor-블록암호-조립소': () => import('./xor-블록암호-조립소/App'),
  '가명화-파이프라인-퍼즐': () => import('./가명화-파이프라인-퍼즐/App'),
  '개인정보-처리-흐름-조립-퍼즐': () => import('./개인정보-처리-흐름-조립-퍼즐/App'),
  '고전-암호-해독가_-카이사르와-스키테일': () => import('./고전-암호-해독가_-카이사르와-스키테일/App'),
  '공유-마스터리_-우리-반-자료-공유-안전하게': () => import('./공유-마스터리_-우리-반-자료-공유-안전하게/App'),
  '공유-선택의-기술_-속도보안편의-균형게임': () => import('./공유-선택의-기술_-속도보안편의-균형게임/App'),
  '공유-순서-퍼즐_-폴더링크프린터': () => import('./공유-순서-퍼즐_-폴더링크프린터/App'),
  '공유의-제왕_-상황별-최적의-공유법': () => import('./공유의-제왕_-상황별-최적의-공유법/App'),
  '공유해도-돼-보호해야-돼': () => import('./공유해도-돼-보호해야-돼/App'),
  '공유해도-될까-3분류-챌린지': () => import('./공유해도-될까-3분류-챌린지/App'),
  '교실-공유기-실험실_-연결ip보안': () => import('./교실-공유기-실험실_-연결ip보안/App'),
  '교실-데이터-맵': () => import('./교실-데이터-맵/index'),
  '규칙-vs-데이터_-코딩-대결': () => import('./규칙-vs-데이터_-코딩-대결/App'),
  '균형-잡기_-정보-보호와-공유': () => import('./균형-잡기_-정보-보호와-공유/App'),
  '그릇-매칭-랩_-변수자료형-분류-게임': () => import('./그릇-매칭-랩_-변수자료형-분류-게임/App'),
  '급식-잔반-예측-미니랩': () => import('./급식-잔반-예측-미니랩/App'),
  '급식간식-군집화-미니랩': () => import('./급식간식-군집화-미니랩/App'),
  '급식실-탐정_-데이터-수집-대작전': () => import('./급식실-탐정_-데이터-수집-대작전/App'),
  '기계학습-트레이드오프-코치': () => import('./기계학습-트레이드오프-코치/App'),
  '길-찾기의-신_-단순화의-힘': () => import('./길-찾기의-신_-단순화의-힘/App'),
  '나는야-보안-컨설턴트_-최적의-방패를-찾아라': () => import('./나는야-보안-컨설턴트_-최적의-방패를-찾아라/App'),
  '나만의-ai-설계소_-기획부터-윤리까지': () => import('./나만의-ai-설계소_-기획부터-윤리까지/App'),
  '나만의-디바이스-만들기': () => import('./나만의-디바이스-만들기/App'),
  '나의-ai-진로-나침반': () => import('./나의-ai-진로-나침반/App'),
  '나의-디지털-진로-로드맵-위저드-2': () => import('./나의-디지털-진로-로드맵-위저드-2/App'),
  '나의-디지털-트윈-농장': () => import('./나의-디지털-트윈-농장/App'),
  '내-앱-보안-설계서-만들기_-수행평가-템플릿': () => import('./내-앱-보안-설계서-만들기_-수행평가-템플릿/App'),
  '내-이웃은-누구-k-nn-시뮬레이터': () => import('./내-이웃은-누구-k-nn-시뮬레이터/App'),
  '내-폰을-지켜라-smishing-defense': () => import('./내-폰을-지켜라-smishing-defense/App'),
  '네트워크-건축가_-스마트-교실-만들기': () => import('./네트워크-건축가_-스마트-교실-만들기/App'),
  '네트워크-장비-도감': () => import('./네트워크-장비-도감/App'),
  '네트워크-핵심요소-마스터리': () => import('./네트워크-핵심요소-마스터리/App'),
  '넷-커넥트-net-connect': () => import('./넷-커넥트-net-connect/App'),
  '능력의-저울_-인간-vs-ai': () => import('./능력의-저울_-인간-vs-ai/App'),
  '대체될까-협업할까-직업-판별-게임': () => import('./대체될까-협업할까-직업-판별-게임/App'),
  '더러운-데이터-세탁소': () => import('./더러운-데이터-세탁소/App'),
  '데이터-가디언_-윤리적-수집가': () => import('./데이터-가디언_-윤리적-수집가/App'),
  '데이터-암호화-101_-우리반-단톡방-지킴이': () => import('./데이터-암호화-101_-우리반-단톡방-지킴이/App'),
  '데이터-탄소-다이어트_-압축-위저드': () => import('./데이터-탄소-다이어트_-압축-위저드/App'),
  '도서관-사서의-하루_-실생활-정렬-챌린지': () => import('./도서관-사서의-하루_-실생활-정렬-챌린지/App'),
  '동아리-캐릭터-카드로-배우는-클래스': () => import('./동아리-캐릭터-카드로-배우는-클래스/App'),
  '등교-최적화-트레이드오프-랩': () => import('./등교-최적화-트레이드오프-랩/App'),
  '등굣길-자동결정-시뮬레이터': () => import('./등굣길-자동결정-시뮬레이터/App'),
  '디지털-보안관_-해킹을-막아라': () => import('./디지털-보안관_-해킹을-막아라/App'),
  '디지털-사회-특성-마스터': () => import('./디지털-사회-특성-마스터/App'),
  '디지털-지문-탐정_-원본을-찾아라': () => import('./디지털-지문-탐정_-원본을-찾아라/App'),
  '디지털-탄소-다이어트': () => import('./디지털-탄소-다이어트/App'),
  '디지털-탐정-진실을-찾아라': () => import('./디지털-탐정-진실을-찾아라/App'),
  '라디오-그룹-미스터리': () => import('./라디오-그룹-미스터리/App'),
  '라면-요리사_-레시피-알고리즘': () => import('./라면-요리사_-레시피-알고리즘/App'),
  '로봇-코딩-연구소_-패턴을-찾아라': () => import('./로봇-코딩-연구소_-패턴을-찾아라/App'),
  '로봇-키우기_-당근과-채찍': () => import('./로봇-키우기_-당근과-채찍/App'),
  '마스터-ip-주소-해독기': () => import('./마스터-ip-주소-해독기/App'),
  '마이데이터-딜레마_-이득-vs-위험': () => import('./마이데이터-딜레마_-이득-vs-위험/App'),
  '머신러닝-카드덱_-규칙을-찾는-공부-친구': () => import('./머신러닝-카드덱_-규칙을-찾는-공부-친구/App'),
  '머신러닝-파이프라인-조립-퍼즐': () => import('./머신러닝-파이프라인-조립-퍼즐/App'),
  '모델-디버깅-위저드': () => import('./모델-디버깅-위저드/App'),
  '무선-기술-선택-회의': () => import('./무선-기술-선택-회의/App'),
  '무선기술-생활탐정': () => import('./무선기술-생활탐정/App'),
  '문자-함정-탐정단': () => import('./문자-함정-탐정단/App'),
  '미래-농장-타이쿤': () => import('./미래-농장-타이쿤/App'),
  '미래-사회-타임머신_-2025-vs-2045': () => import('./미래-사회-타임머신_-2025-vs-2045/App'),
  '미래-직업-연구소_-나만의-커리어-믹서': () => import('./미래-직업-연구소_-나만의-커리어-믹서/App'),
  '미세먼지-예보관': () => import('./미세먼지-예보관/App'),
  '보물섬-탐험대_-그래프-탐색': () => import('./보물섬-탐험대_-그래프-탐색/App'),
  '보호-vs-공유_-개념-마스터-트레이너': () => import('./보호-vs-공유_-개념-마스터-트레이너/App'),
  '분류-스쿼드-classification-squad': () => import('./분류-스쿼드-classification-squad/App'),
  '분류냐-회귀냐_-문제-해결사': () => import('./분류냐-회귀냐_-문제-해결사/App'),
  '블록-암호-연구소': () => import('./블록-암호-연구소/App'),
  '비밀-쪽지-대작전': () => import('./비밀-쪽지-대작전/App'),
  '비밀-쪽지-압축기-the-message-shrinker': () => import('./비밀-쪽지-압축기-the-message-shrinker/App'),
  '비지도학습-카드-덱_-라벨-없는-세계': () => import('./비지도학습-카드-덱_-라벨-없는-세계/App'),
  '비트-팜_-내-손안의-농장': () => import('./비트-팜_-내-손안의-농장/App'),
  '빌드-잇_-나만의-ai-에이전트': () => import('./빌드-잇_-나만의-ai-에이전트/App'),
  '사회-문제-해결사_-테크로-세상을-바꾸다': () => import('./사회-문제-해결사_-테크로-세상을-바꾸다/App'),
  '삽입-정렬-프로젝트-위저드_-플레이리스트-정리기': () => import('./삽입-정렬-프로젝트-위저드_-플레이리스트-정리기/App'),
  '상태목표-분해-마스터': () => import('./상태목표-분해-마스터/App'),
  '선발전-정렬-코치_-선택-정렬-마스터리': () => import('./선발전-정렬-코치_-선택-정렬-마스터리/App'),
  '센서에서-행동까지': () => import('./센서에서-행동까지/App'),
  '수면데이터-추적기_-dnpc-해부-실험실': () => import('./수면데이터-추적기_-dnpc-해부-실험실/App'),
  '수행평가-메이커_-안전한-공유-프로젝트': () => import('./수행평가-메이커_-안전한-공유-프로젝트/App'),
  '수행평가-메이커_-안전한-정보-공유-프로젝트-위저드': () => import('./수행평가-메이커_-안전한-정보-공유-프로젝트-위저드/App'),
  '수행평가-위저드_-나만의-학생-데이터-카드': () => import('./수행평가-위저드_-나만의-학생-데이터-카드/App'),
  '수행평가-위저드_-우리-반-출석부-설계': () => import('./수행평가-위저드_-우리-반-출석부-설계/App'),
  '숨은-스마트-사물-찾기-주제': () => import('./숨은-스마트-사물-찾기-주제/App'),
  '스마트-라이프': () => import('./스마트-라이프/App'),
  '스마트-라이프-밸런스-smart-life-balance': () => import('./스마트-라이프-밸런스-smart-life-balance/App'),
  '스마트-사서_-정렬과-탐색': () => import('./스마트-사서_-정렬과-탐색/App'),
  '스마트-조명-트레이드오프-랩': () => import('./스마트-조명-트레이드오프-랩/App'),
  '스마트-홈-배관공': () => import('./스마트-홈-배관공/App'),
  '스마트교실-iot-실험실': () => import('./스마트교실-iot-실험실/App'),
  '스마트시티-위저드-smart-city-wizard': () => import('./스마트시티-위저드-smart-city-wizard/App'),
  '스마트홈-선택의-기술': () => import('./스마트홈-선택의-기술/App'),
  '스미싱피싱-방어-훈련장': () => import('./스미싱피싱-방어-훈련장/App'),
  '스쿨-해커톤_-우리-학교-업그레이드': () => import('./스쿨-해커톤_-우리-학교-업그레이드/App'),
  '스타트업-ceo_-보안-vs-성장': () => import('./스타트업-ceo_-보안-vs-성장/App'),
  '스트리머-타이쿤': () => import('./스트리머-타이쿤/App'),
  '스팸-메일-탐정_-특징feature로-잡아내기': () => import('./스팸-메일-탐정_-특징feature로-잡아내기/App'),
  '시간여행자의-iot-도감': () => import('./시간여행자의-iot-도감/App'),
  '알고리즘-베이직_-탐색의-정석': () => import('./알고리즘-베이직_-탐색의-정석/App'),
  '알고리즘-실험실_-데이터가-움직이는-원리': () => import('./알고리즘-실험실_-데이터가-움직이는-원리/App'),
  '암호-방식-감별사_-이건-어떤-암호지': () => import('./암호-방식-감별사_-이건-어떤-암호지/App'),
  '암호-해독가-the-code-breaker': () => import('./암호-해독가-the-code-breaker/App'),
  '업다운-ai-대결': () => import('./업다운-ai-대결/App'),
  '에이전트-감별사_-규칙봇-vs-지능봇': () => import('./에이전트-감별사_-규칙봇-vs-지능봇/App'),
  '에이전트-루프-퍼즐': () => import('./에이전트-루프-퍼즐/App'),
  '에이전트-아카데미_-단순-vs-지능': () => import('./에이전트-아카데미_-단순-vs-지능/App'),
  '에이전트-아키텍트': () => import('./에이전트-아키텍트/App'),
  '에이전트-카드덱_-지능-에이전트-마스터리': () => import('./에이전트-카드덱_-지능-에이전트-마스터리/App'),
  '에코-그리드-매니저': () => import('./에코-그리드-매니저/App'),
  '에코-라이트_-도시의-밤을-밝혀라': () => import('./에코-라이트_-도시의-밤을-밝혀라/App'),
  '역량-레이더_-내-진로-스킬을-수치로-보기': () => import('./역량-레이더_-내-진로-스킬을-수치로-보기/App'),
  '역할-레벨업-카드_-인간ai-역할-마스터리': () => import('./역할-레벨업-카드_-인간ai-역할-마스터리/App'),
  '연결의-달인_-내-ip를-찾아서': () => import('./연결의-달인_-내-ip를-찾아서/App'),
  '열쇠의-미스터리_-쇼핑몰-로그인-대소동': () => import('./열쇠의-미스터리_-쇼핑몰-로그인-대소동/App'),
  '예_아니요-탐정_-의사결정트리': () => import('./예_아니요-탐정_-의사결정트리/App'),
  '오늘의-iot-미션': () => import('./오늘의-iot-미션/App'),
  '오늘의-ml-랜덤-미션': () => import('./오늘의-ml-랜덤-미션/App'),
  '오늘의-ml-미션_-날짜-시드-고정-도전장': () => import('./오늘의-ml-미션_-날짜-시드-고정-도전장/App'),
  '오늘의-oop-미션': () => import('./오늘의-oop-미션/App'),
  '오늘의-공존-미션': () => import('./오늘의-공존-미션/App'),
  '오늘의-네트워크-미션_-dhcp로-충돌-막기': () => import('./오늘의-네트워크-미션_-dhcp로-충돌-막기/App'),
  '오늘의-산불-미션_-센서-배치로-조기-발견하기': () => import('./오늘의-산불-미션_-센서-배치로-조기-발견하기/App'),
  '오늘의-정렬-미션': () => import('./오늘의-정렬-미션/App'),
  '오늘의-탐색-미션': () => import('./오늘의-탐색-미션/App'),
  '우리-반-공유-헌장-만들기_-협업-규칙-위저드': () => import('./우리-반-공유-헌장-만들기_-협업-규칙-위저드/App'),
  '우리-학교-ai-해결사': () => import('./우리-학교-ai-해결사/App'),
  '우리-학교-저작권-지킴이-ccl-maker': () => import('./우리-학교-저작권-지킴이-ccl-maker/App'),
  '우주-여행-플래너-space-travel-planner': () => import('./우주-여행-플래너-space-travel-planner/App'),
  '위협-데이터베이스': () => import('./위협-데이터베이스/App'),
  '유무선-네트워크-완전-정복': () => import('./유무선-네트워크-완전-정복/App'),
  '유선-vs-무선-결정-실험실': () => import('./유선-vs-무선-결정-실험실/App'),
  '이건-어떤-학습-60초-판별-게임': () => import('./이건-어떤-학습-60초-판별-게임/App'),
  '이상치-탐정_-이-점-튀었는데': () => import('./이상치-탐정_-이-점-튀었는데/App'),
  '이진-탐색-판별-게임': () => import('./이진-탐색-판별-게임/App'),
  '인맥의-중심_-관계망-만들기': () => import('./인맥의-중심_-관계망-만들기/App'),
  '일일-탐색-드릴_-오늘의-미션': () => import('./일일-탐색-드릴_-오늘의-미션/App'),
  '임계값-딜레마_-위험-경보-결정하기': () => import('./임계값-딜레마_-위험-경보-결정하기/App'),
  '임계값-튜너_-손뼉-전등': () => import('./임계값-튜너_-손뼉-전등/App'),
  '입출력-루트-빌더': () => import('./입출력-루트-빌더/App'),
  '저작권과-공유의-세계': () => import('./저작권과-공유의-세계/App'),
  '전송-방식-판별전': () => import('./전송-방식-판별전/App'),
  '정렬-체육관-sortgym': () => import('./정렬-체육관-sortgym/App'),
  '정렬-탐정_-사라진-알고리즘을-찾아라': () => import('./정렬-탐정_-사라진-알고리즘을-찾아라/App'),
  '정보-보안-가디언-아카데미': () => import('./정보-보안-가디언-아카데미/App'),
  '정보-보안-지킴이': () => import('./정보-보안-지킴이/App'),
  '정보-보호의-성': () => import('./정보-보호의-성/App'),
  '지각-대탈출_-시간의-마법사': () => import('./지각-대탈출_-시간의-마법사/App'),
  '지능-에이전트-마스터': () => import('./지능-에이전트-마스터/App'),
  '직업-타임머신': () => import('./직업-타임머신/App'),
  '진로-에이전트-기획-위저드': () => import('./진로-에이전트-기획-위저드/App'),
  '최적의-선을-찾아라-linear-regression': () => import('./최적의-선을-찾아라-linear-regression/App'),
  '축제-기획의-달인_-분해의-미학': () => import('./축제-기획의-달인_-분해의-미학/App'),
  '축제-운영-ai_-밸런스-게임': () => import('./축제-운영-ai_-밸런스-게임/App'),
  '카이사르-암호_-사물함-쪽지-암호기': () => import('./카이사르-암호_-사물함-쪽지-암호기/App'),
  '커리어-밸런스-게임_-미래성-vs-안정-vs-흥미': () => import('./커리어-밸런스-게임_-미래성-vs-안정-vs-흥미/App'),
  '퀵-정렬-마스터_-피벗의-전략가': () => import('./퀵-정렬-마스터_-피벗의-전략가/App'),
  '키-선택-회의_-속도-vs-보안-vs-관리': () => import('./키-선택-회의_-속도-vs-보안-vs-관리/App'),
  '탐색-알고리즘-마스터리': () => import('./탐색-알고리즘-마스터리/App'),
  '탐색-전략-컨설턴트-search-strategy-consultant': () => import('./탐색-전략-컨설턴트-search-strategy-consultant/App'),
  '탐색-절차-조립소': () => import('./탐색-절차-조립소/App'),
  '탐정-ai_-숨은-패턴-찾기': () => import('./탐정-ai_-숨은-패턴-찾기/App'),
  '톡톡-용량-줄이기_-압축-vs-암호화': () => import('./톡톡-용량-줄이기_-압축-vs-암호화/App'),
  '트리-빌더_-루브릭-퍼즐': () => import('./트리-빌더_-루브릭-퍼즐/App'),
  '파이프라인-조립소': () => import('./파이프라인-조립소/App'),
  '패킷의-모험_-서울에서-뉴욕까지': () => import('./패킷의-모험_-서울에서-뉴욕까지/App'),
  '팩트체크_-가짜-그래프를-찾아라': () => import('./팩트체크_-가짜-그래프를-찾아라/App'),
  '펭귄과-기후-연구소': () => import('./펭귄과-기후-연구소/App'),
  '편의점-할인-판별-게임': () => import('./편의점-할인-판별-게임/App'),
  '포맷-선택-챌린지': () => import('./포맷-선택-챌린지/App'),
  '프로젝트-위저드_-수질-관리-에이전트': () => import('./프로젝트-위저드_-수질-관리-에이전트/App'),
  '픽셀-아트-마스터_-플로피-에디션': () => import('./픽셀-아트-마스터_-플로피-에디션/App'),
  '하루-1개-입출력-수리공': () => import('./하루-1개-입출력-수리공/App'),
  '학교-소개-영상-제작-위저드': () => import('./학교-소개-영상-제작-위저드/App'),
  '합병-정렬-조립-퍼즐_-분할-정렬-합병-라인': () => import('./합병-정렬-조립-퍼즐_-분할-정렬-합병-라인/App'),
  '혈압-루틴-플로우-퍼즐': () => import('./혈압-루틴-플로우-퍼즐/App'),
  '협업-트레이드오프-스튜디오': () => import('./협업-트레이드오프-스튜디오/App'),
  '황금귀-챌린지-the-golden-ear-challenge': () => import('./황금귀-챌린지-the-golden-ear-challenge/App'),
  '회귀-랩_-내-성적-탄소-예측': () => import('./회귀-랩_-내-성적-탄소-예측/App'),
  // 새로운 앱을 추가할 때 여기에만 추가하면 됩니다
  // 'new-app-id': () => import('./new-app-folder/NewApp'),
}

/**
 * 앱 ID로 컴포넌트를 동적으로 로드합니다
 */
export function getAppComponent(appId: string): AppComponent | null {
  const loader = appComponents[appId]
  if (!loader) {
    return null
  }

  // 동적 import로 컴포넌트 로드 (최적화된 설정)
  return dynamic(loader, {
    loading: () => (
      <div className="flex items-center justify-center min-h-screen bg-white">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-gray-600 font-medium">앱을 불러오는 중...</p>
        </div>
      </div>
    ),
    ssr: false, // 클라이언트 사이드에서만 렌더링
    // 로딩 최적화를 위한 추가 옵션
  })
}

/**
 * 등록된 모든 앱 ID 목록을 반환합니다
 */
export function getRegisteredAppIds(): string[] {
  return Object.keys(appComponents)
}

/**
 * 앱이 등록되어 있는지 확인합니다
 */
export function isAppRegistered(appId: string): boolean {
  return appId in appComponents
}

