import { ClassificationType, ConceptCardData, GameCard, QuizQuestion } from './types';

export const LEVEL_THRESHOLDS = [0, 100, 300, 600, 1000, 1500, 2100, 2800, 3600, 5000];

export const CONCEPTS: ConceptCardData[] = [
  {
    id: 'share',
    title: '공유해야 할 정보',
    definition: '개인정보를 포함하지 않으며, 사회 구성원에게 유익하거나 공익을 증진시키는 정보.',
    keywords: ['공익성', '유용성', '비식별'],
    example: '폭염 주의보 재난 문자, 도서관 휴관 안내, 지하철 지연 정보',
    misconception: '유용한 정보라면 내 친구의 정보도 그냥 공유해도 된다? (X)',
    question: '이 정보를 모르는 사람이 봤을 때 누군가 특정되지 않는가?',
  },
  {
    id: 'protect',
    title: '보호해야 할 정보',
    definition: '유출 시 개인, 단체, 국가에 재산적·정신적 피해를 줄 수 있어 공개를 제한해야 하는 정보.',
    keywords: ['피해 가능성', '프라이버시', '보안'],
    example: '비밀번호, 친구의 엽기 사진, 주민등록번호, 집 주소',
    misconception: '친한 친구끼리는 비밀번호를 공유해도 안전하다? (X)',
    question: '이 정보가 악용되면 나나 타인이 피해를 입을 수 있는가?',
  },
  {
    id: 'conditional',
    title: '조건부 공유',
    definition: '원칙적으로 보호해야 하지만, 식별 요소를 제거(가명·익명 처리)하거나 동의를 얻은 후 제한적으로 공유 가능한 정보.',
    keywords: ['가명처리', '동의', '마스킹'],
    example: '이름을 가린 성적 분포표, 얼굴을 가린 단체 사진',
    misconception: '모자이크만 하면 무조건 올려도 된다? (X, 맥락상 유추 가능하면 위험)',
    question: '민감한 부분을 가리거나 당사자의 허락을 받았는가?',
  },
  {
    id: 'pii',
    title: '개인정보 (PII)',
    definition: '살아있는 개인을 알아볼 수 있는 정보. 해당 정보만으로 특정 못해도 다른 정보와 결합해 식별 가능하면 포함.',
    keywords: ['식별성', '결합 가능성', '고유식별정보'],
    example: '이름, 전화번호, 영상, 생체 정보, 학번+이름 조합',
    misconception: '이름만 없으면 개인정보가 아니다? (X, 학번이나 특징으로 식별 가능)',
    question: '이 정보를 통해 "누구인지" 알아낼 수 있는가?',
  },
  {
    id: 'digital_footprint',
    title: '디지털 발자국',
    definition: '인터넷을 사용하면서 남기는 흔적. 삭제해도 서버나 타인의 캡처본에 남아 완전히 지우기 어렵다.',
    keywords: ['영속성', '확산성', '기록'],
    example: 'SNS 댓글, 방문 기록, 업로드한 사진, 검색 기록',
    misconception: '내가 쓴 글은 내가 지우면 사라진다? (X)',
    question: '이 기록이 10년 뒤에 공개되어도 부끄럽지 않은가?',
  },
  {
    id: 'ethics',
    title: '정보 윤리',
    definition: '정보 사회에서 구성원이 지켜야 할 올바른 가치관과 행동 양식.',
    keywords: ['존중', '책임', '저작권'],
    example: '악플 달지 않기, 출처 명시하기, 타인의 창작물 존중',
    misconception: '익명 게시판에서는 욕설을 해도 모른다? (X, 추적 가능 및 윤리 위반)',
    question: '나의 행동이 타인에게 상처가 되지 않는가?',
  },
];

export const GAME_CARDS: GameCard[] = [
  { id: 1, content: "내일 급식 메뉴 식단표", type: ClassificationType.SHARE, reason: "모두에게 유용하고 개인정보가 없음", keywords: ["공익성", "정보공유"] },
  { id: 2, content: "우리 반 친구 얼굴이 나온 단체 사진 (동의 없음)", type: ClassificationType.PROTECT, reason: "초상권 침해 및 범죄 악용 우려", keywords: ["초상권", "개인정보"] },
  { id: 3, content: "친구 이름이 적힌 모의고사 성적표", type: ClassificationType.PROTECT, reason: "민감한 개인정보(성적) 노출", keywords: ["민감정보", "프라이버시"] },
  { id: 4, content: "이름과 번호를 가린 우리 반 성적 평균표", type: ClassificationType.CONDITIONAL, reason: "개인 식별 요소를 제거하여 통계적 가치만 공유", keywords: ["가명처리", "통계"] },
  { id: 5, content: "우리 동네 코로나 확진자 이동 경로 (개인 특정 불가)", type: ClassificationType.SHARE, reason: "공공 안전을 위한 정보 (사생활 침해 최소화 전제)", keywords: ["공익", "안전"] },
  { id: 6, content: "담임 선생님 휴대폰 번호", type: ClassificationType.PROTECT, reason: "업무 외 사생활 침해 우려", keywords: ["연락처", "사생활"] },
  { id: 7, content: "지하철 파업으로 인한 운행 지연 안내", type: ClassificationType.SHARE, reason: "다수에게 필요한 교통 정보", keywords: ["유용성", "긴급정보"] },
  { id: 8, content: "친구 자는 모습 몰래 찍은 사진", type: ClassificationType.PROTECT, reason: "명백한 초상권 침해 및 인격 모독 가능성", keywords: ["초상권", "사이버폭력"] },
  { id: 9, content: "동아리 홍보 포스터 (담당자: 오픈채팅 링크)", type: ClassificationType.CONDITIONAL, reason: "개인 번호 대신 안심 링크 사용 권장", keywords: ["대체수단", "홍보"] },
  { id: 10, content: "여행 가서 찍은 풍경 사진 (사람 없음, 위치 태그 끔)", type: ClassificationType.SHARE, reason: "개인정보 없음, 저작권자 본인", keywords: ["비식별", "창작물"] },
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "다음 중 SNS에 '그대로' 공유해도 안전한 정보는?",
    options: ["친구의 주민등록번호 뒷자리", "우리 집 현관 비밀번호", "내일 학교 급식 메뉴", "가족 여행 중 실시간 위치 태그"],
    correctIndex: 2,
    explanation: "급식 메뉴는 개인정보가 포함되지 않은 공공 정보입니다. 나머지는 사생활 침해나 범죄 악용 우려가 있습니다.",
    conceptId: 'share',
    difficulty: '쉬움',
  },
  {
    id: 2,
    question: "단체 사진을 SNS에 올리기 전 가장 올바른 행동은?",
    options: ["그냥 올린다.", "친구들이 잘 나온 것 같으면 올린다.", "친구들에게 허락을 구하거나, 싫다는 친구는 가려준다.", "작게 나온 사람은 무시한다."],
    correctIndex: 2,
    explanation: "초상권 보호를 위해 당사자의 동의를 구하는 것이 필수적입니다. 동의하지 않으면 모자이크(가명처리) 해야 합니다.",
    conceptId: 'conditional',
    difficulty: '보통',
  },
  {
    id: 3,
    question: "'개인정보'에 해당하지 않는 것은?",
    options: ["홍길동의 얼굴 사진", "010-1234-5678 전화번호", "대한민국의 수도는 서울이다", "학번 1101 + 이름 김철수"],
    correctIndex: 2,
    explanation: "'대한민국의 수도는 서울이다'는 일반적인 사실 정보로, 특정 개인을 식별할 수 없습니다.",
    conceptId: 'pii',
    difficulty: '쉬움',
  },
  {
    id: 4,
    question: "개인정보를 가명처리(익명화)하여 공유하는 '조건부 공유'의 예시로 적절한 것은?",
    options: ["친구 이름은 가렸지만 얼굴은 그대로 둔 사진", "이름을 가린 전교생 키/몸무게 분포 데이터", "주민번호 뒷자리만 가린 등본", "비밀번호 앞자리만 가린 메모"],
    correctIndex: 1,
    explanation: "통계 데이터 작성을 위해 식별자(이름)를 제거하고 공유하는 것은 적절한 조건부 공유 사례입니다. 얼굴이나 주민번호 앞자리는 여전히 개인을 특정할 위험이 높습니다.",
    conceptId: 'conditional',
    difficulty: '도전',
  },
  {
    id: 5,
    question: "디지털 발자국에 대한 설명으로 틀린 것은?",
    options: ["한번 인터넷에 올린 정보는 완전히 삭제하기 어렵다.", "내가 지우면 서버에서도 즉시 사라진다.", "나의 검색 기록도 디지털 발자국에 포함된다.", "입학 사정관이나 채용 담당자가 볼 수도 있다."],
    correctIndex: 1,
    explanation: "내가 지워도 서버 백업, 다른 사람의 캡처, 아카이브 사이트 등에 남아 있을 수 있습니다.",
    conceptId: 'digital_footprint',
    difficulty: '보통',
  },
  {
    id: 6,
    question: "다음 상황 중 '보호해야 할 정보'로 분류하기 가장 애매한 것은?",
    options: ["나의 일기장 내용", "내 통장 잔고", "학교 홈페이지에 게시된 공식 학사일정", "친구와 나눈 1:1 비밀 카톡"],
    correctIndex: 2,
    explanation: "학교 공식 학사일정은 구성원 모두가 알아야 할 정보로 '공유'에 가깝습니다. 나머지는 사적인 영역입니다.",
    conceptId: 'share',
    difficulty: '보통',
  },
  {
    id: 7,
    question: "SNS에 공연 티켓 인증샷을 올릴 때 가려야 할 정보는?",
    options: ["공연 제목", "공연 일시", "바코드 및 예매번호", "공연장 이름"],
    correctIndex: 2,
    explanation: "바코드나 예매번호가 노출되면 타인이 티켓을 도용하거나 취소할 수 있습니다.",
    conceptId: 'protect',
    difficulty: '도전',
  },
  {
    id: 8,
    question: "'잊혀질 권리'와 가장 관련 깊은 개념은?",
    options: ["공유해야 할 정보", "디지털 발자국", "공익 제보", "저작권"],
    correctIndex: 1,
    explanation: "디지털 발자국이 영구적으로 남는 문제에 대응하여, 자신이 원하지 않는 정보를 삭제해달라고 요구할 권리입니다.",
    conceptId: 'digital_footprint',
    difficulty: '보통',
  },
  {
    id: 9,
    question: "다음 중 사이버 학교폭력이 될 수 있는 정보 공유는?",
    options: ["친구가 대회에서 상 받은 소식을 축하하며 공유", "친구가 실수하는 영상을 '웃긴 영상'이라며 단톡방 공유", "봉사활동 모집 공고 공유", "잃어버린 물건 찾는 글 공유"],
    correctIndex: 1,
    explanation: "당사자가 수치심을 느낄 수 있는 영상을 동의 없이 유포하는 것은 사이버 폭력에 해당합니다.",
    conceptId: 'ethics',
    difficulty: '쉬움',
  },
  {
    id: 10,
    question: "위치 기반 서비스를 사용할 때 주의할 점으로 옳은 것은?",
    options: ["항상 모든 앱에 위치 권한을 허용한다.", "실시간 위치를 SNS에 전체 공개로 올린다.", "꼭 필요한 앱에만 '사용 중에만 허용'으로 설정한다.", "집 주소가 나오게 지도 캡처를 올린다."],
    correctIndex: 2,
    explanation: "불필요한 위치 추적을 막기 위해 최소한의 권한만 부여하고, 실시간 위치 노출은 범죄 표적이 될 수 있어 주의해야 합니다.",
    conceptId: 'protect',
    difficulty: '도전',
  },
];
