import { TechInfo, Scenario, QuizQuestion } from './types';

export const TECH_INFO: TechInfo[] = [
  {
    id: 'symmetric',
    name: '대칭키 암호화 (Symmetric Key)',
    description: '암호화와 복호화에 같은 키를 사용하는 방식입니다.',
    pros: ['처리 속도가 매우 빠름', '대용량 데이터 처리에 적합', '구현이 비교적 단순'],
    cons: ['키 배송(교환) 문제 존재', '사용자 증가 시 관리할 키 개수가 급증'],
    bestUse: '대용량 파일 전송, 내부 데이터베이스 암호화, 친구 간의 비밀 영화 공유',
  },
  {
    id: 'asymmetric',
    name: '공개키 암호화 (Asymmetric Key)',
    description: '공개키로 암호화하고 개인키로 복호화하는 방식입니다 (또는 반대).',
    pros: ['키 배송 문제 해결', '전자 서명(부인 방지) 가능', '보안성 높음'],
    cons: ['수학적 연산으로 인해 속도가 느림', '대용량 처리에 부적합'],
    bestUse: '키 교환, 전자 서명, 금융 거래 인증, 소량의 중요 정보 전송',
  },
  {
    id: 'hash',
    name: '해시 함수 (Hash Function)',
    description: '임의의 데이터를 고정된 길이의 값으로 변환하는 단방향 함수입니다.',
    pros: ['데이터 위변조 즉시 확인 가능 (무결성)', '복호화 불가능(일방향성)으로 비밀번호 저장에 안전'],
    cons: ['원문을 복구할 수 없음 (암호화 통신 용도 아님)', '충돌(Collision) 가능성(극히 낮음)'],
    bestUse: '비밀번호 저장, 소프트웨어 위변조 검사, 전자 서명 보조',
  },
];

export const SCENARIOS: Scenario[] = [
  {
    id: 1,
    client: '국방부 장관',
    role: '군사 작전 사령부',
    description: '적진에 침투한 요원에게 1급 기밀 작전 명령서를 보내야 합니다. 파일 크기는 작지만, 절대 적에게 노출되어서는 안 되며, 내가 보낸 것이 확실해야(인증) 합니다.',
    reqSecurity: 10,
    reqSpeed: 3,
    reqConvenience: 1,
    correctTech: 'asymmetric',
    budgetSensitivity: 'low',
    explanation: '보안과 인증(부인 방지)이 핵심입니다. 속도가 느려도 공개키 기반의 전자서명과 암호화가 필요합니다.',
  },
  {
    id: 2,
    client: '영화 제작사 대표',
    role: '미디어 센터',
    description: '개봉 전인 4K 고화질 영화 원본 파일(500GB)을 편집실로 전송해야 합니다. 유출되면 안 되지만, 전송 시간이 너무 오래 걸리면 개봉일을 못 맞춥니다.',
    reqSecurity: 7,
    reqSpeed: 10,
    reqConvenience: 5,
    correctTech: 'symmetric',
    budgetSensitivity: 'medium',
    explanation: '대용량 파일은 공개키로 암호화하면 며칠이 걸릴 수도 있습니다. 키만 안전하게 전달된다면 대칭키가 효율적입니다.',
  },
  {
    id: 3,
    client: '웹사이트 개발자',
    role: 'IT 스타트업',
    description: '회원가입 기능을 만들고 있습니다. DB가 해킹당하더라도 사용자의 비밀번호가 노출되지 않도록 저장하고 싶습니다.',
    reqSecurity: 8,
    reqSpeed: 9,
    reqConvenience: 8,
    correctTech: 'hash',
    budgetSensitivity: 'high',
    explanation: '비밀번호는 복호화될 필요가 없습니다. 해시 함수를 사용하여 단방향 암호화하여 저장해야 합니다.',
  },
  {
    id: 4,
    client: '은행장',
    role: '글로벌 뱅킹',
    description: '수백만 명의 고객이 접속합니다. 초기 접속 시 안전하게 채널을 형성하고(키 교환), 그 이후에는 빠른 거래 데이터를 주고받아야 합니다.',
    reqSecurity: 9,
    reqSpeed: 9,
    reqConvenience: 7,
    correctTech: 'hybrid', // Special logic handled in component
    budgetSensitivity: 'low',
    explanation: '현대 웹(HTTPS/TLS)은 공개키로 대칭키를 안전하게 교환하고, 실제 데이터는 대칭키로 통신하는 하이브리드 방식을 씁니다.',
  }
];

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: '대칭키 암호화 방식의 가장 큰 단점은 무엇인가요?',
    options: ['암호화 속도가 느리다', '복호화가 불가능하다', '키 배송(교환) 문제가 있다', '데이터 크기가 커진다'],
    correctAnswer: 2,
    explanation: '대칭키는 송신자와 수신자가 같은 키를 가져야 하므로, 안전하게 키를 전달하는 것이 어렵습니다.',
  },
  {
    id: 2,
    question: '다음 중 "기밀성(Confidentiality)"과 관련이 깊은 것은?',
    options: ['해시 함수', '암호화', '디지털 포렌식', '가용성'],
    correctAnswer: 1,
    explanation: '암호화는 허가되지 않은 사람이 내용을 볼 수 없게 하여 기밀성을 보장합니다.',
  },
  {
    id: 3,
    question: '해시 함수의 특징인 "쇄도 효과(Avalanche Effect)"란?',
    options: ['입력값이 조금만 바뀌어도 출력값이 완전히 달라지는 성질', '입력값이 같으면 출력값도 같은 성질', '출력값으로 입력값을 유추할 수 있는 성질', '눈사태처럼 데이터가 사라지는 성질'],
    correctAnswer: 0,
    explanation: '입력의 미세한 변화가 출력 전체에 영향을 미치는 성질을 쇄도 효과라고 합니다.',
  },
  {
    id: 4,
    question: '공개키 암호화 알고리즘이 아닌 것은?',
    options: ['RSA', 'ECC', 'AES', 'ElGamal'],
    correctAnswer: 2,
    explanation: 'AES는 대표적인 대칭키 암호화 알고리즘입니다.',
  },
  {
    id: 5,
    question: '전자서명에서 서명자가 사용하는 키는?',
    options: ['수신자의 공개키', '수신자의 개인키', '송신자의 공개키', '송신자의 개인키'],
    correctAnswer: 3,
    explanation: '전자서명은 본인만 할 수 있어야 하므로 송신자의 개인키로 암호화(서명)합니다.',
  },
  {
    id: 6,
    question: '비밀번호를 저장할 때 솔트(Salt)를 사용하는 이유는?',
    options: ['비밀번호 길이를 줄이기 위해', '레인보우 테이블 공격을 방어하기 위해', '암호화 속도를 높이기 위해', '사용자가 비밀번호를 잊어버렸을 때 알려주기 위해'],
    correctAnswer: 1,
    explanation: '같은 비밀번호라도 Salt를 섞으면 다른 해시값이 생성되어 미리 계산된 해시 테이블(레인보우 테이블) 공격을 막을 수 있습니다.',
  },
  {
    id: 7,
    question: '랜섬웨어(Ransomware)의 주요 공격 방식은?',
    options: ['사용자 파일을 암호화하고 복호화 키 대가로 금전을 요구한다', '컴퓨터 하드웨어를 물리적으로 파괴한다', '네트워크 속도를 느리게 한다', '가짜 백신을 설치한다'],
    correctAnswer: 0,
    explanation: '랜섬웨어는 파일을 무단으로 암호화하여 인질로 잡는 악성코드입니다.',
  },
  {
    id: 8,
    question: '다음 중 양자 컴퓨터의 등장으로 가장 위협받는 암호 기술은?',
    options: ['OTP (One Time Pad)', 'RSA (소인수분해 기반 공개키)', '양자 키 분배', '물리적 보안'],
    correctAnswer: 1,
    explanation: '양자 컴퓨터(쇼어 알고리즘)는 소인수분해를 매우 빠르게 처리할 수 있어 RSA와 같은 현재의 공개키 암호체계를 위협합니다.',
  },
  {
    id: 9,
    question: '정보보안의 3요소(CIA)에 해당하지 않는 것은?',
    options: ['기밀성 (Confidentiality)', '무결성 (Integrity)', '가용성 (Availability)', '익명성 (Anonymity)'],
    correctAnswer: 3,
    explanation: '정보보안의 3요소는 기밀성, 무결성, 가용성입니다.',
  },
  {
    id: 10,
    question: '블록체인 기술의 핵심이 되는 암호 기술은?',
    options: ['해시 함수와 전자서명', '대칭키 암호화만 사용', '스테가노그래피', '단순 치환 암호'],
    correctAnswer: 0,
    explanation: '블록체인은 블록 연결을 위한 해시 함수와 거래 증명을 위한 전자서명(공개키) 기술을 핵심으로 사용합니다.',
  },
];